modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"

[[mods]]
modId="engiesvanillaextras"
version="12.27.24"
displayName="[Dev]Engie(Games)'s Vanilla Extras"
credits="VanillaTweaks (TPA datapack usage.)"
displayURL="https://twitch.tv/engiegames"
authors="[Dev]Engie(Games)"
description="credits are given!"

[[dependencies.engiesvanillaextras]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




