modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"

[[mods]]
modId="engiesvanillaextras"
version="12.29.24"
displayName="[Dev]Engie(Games)'s Vanilla Extras"
credits="VanillaTweaks Team (TPA datapack usage.), PuckiSilver (Keep Some Inventory Datapack)"
displayURL="https://twitch.tv/engiegames"
logoFile="logo.png"
authors="[Dev]Engie(Games)"
description="Check them out, just go on!"

[[dependencies.engiesvanillaextras]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




